- name: Create database task-12-db with user task-12-user
  hosts: DBServers
  become: true
  vars:
    mysql_root_username: root
    mysql_root_password: "Test123!"
    mysql_db_name: task-12-db
    mysql_user_name: task-12-user
    mysql_user_password: "Test123!"
  tasks:
    - name: Install pip package manager
      yum:
        name: python3-pip
        state: present
    - name: Install pymysql module
      pip:
        name: pymysql
        state: present
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Create MySQL database task-12-db
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_root_username }}"
        login_password: "{{ mysql_root_password }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Create MySQL user task-12-user with all privileges on task-12-db
      mysql_user:
        name: "{{ mysql_user_name }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        state: present
        login_user: "{{ mysql_root_username }}"
        login_password: "{{ mysql_root_password }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3