- name: DB servers playbook
  hosts: DBServers
  become: yes
  tasks:
    - name: Copy sh script
      copy:
        src: mysql_installation.sh
        dest: /home/ec2-user/mysql_installation.sh
        owner: root
        group: root
        mode: 0777
    - name: Run sh script
      shell: /home/ec2-user/mysql_installation.sh
    - name: Install mysql
      dnf:
        name: mysql-community-server
        state: latest