---
- name: Verify connection to MySQL database servers
  hosts: WebServers
  gather_facts: false

  tasks:
    - name: Check MySQL connection via Telnet (3.67.185.1)
      wait_for:
        host: 3.67.185.1
        port: 3306
        delay: 5
        timeout: 10
        state: started
        msg: "MySQL database server (3.67.185.1) is not reachable on port 3306"

      register: result_1

    - name: Check MySQL connection via Telnet (3.126.50.202)
      wait_for:
        host: 3.126.50.202
        port: 3306
        delay: 5
        timeout: 10
        state: started
        msg: "MySQL database server (3.126.50.202) is not reachable on port 3306"

      register: result_2

    - name: Display connection status
      debug:
        var: result_1

    - name: Display connection status
      debug:
        var: result_2
