- name: Verify MySQL connection
  hosts: WebServers
  tasks:
    - name: Install telnet
      become: true
      yum:
        name: telnet
        state: present

    - name: Verify MySQL connection (3.67.185.1)
      shell: echo "quit" | telnet 3.67.185.1 3306
      ignore_errors: true
      register: telnet_output_1
      changed_when: false

    - name: Verify MySQL connection (3.126.50.202)
      shell: echo "quit" | telnet 3.126.50.202 3306
      ignore_errors: true
      register: telnet_output_2
      changed_when: false

    - name: Display connection status
      debug:
        msg: |
          MySQL connection status:
            - 3.67.185.1: {{ 'SUCCESS' if telnet_output_1.stdout | regex_search('Connected to') else 'FAILURE' }}
            - 3.126.50.202: {{ 'SUCCESS' if telnet_output_2.stdout | regex_search('Connected to') else 'FAILURE' }}
